plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

def expoBeaconPackage = new groovy.json.JsonSlurper().parse(file('../package.json'))

group = 'expo.modules.beacon'
version = expoBeaconPackage.version

android {
  namespace "expo.modules.beacon"
  defaultConfig {
    versionCode 1
    versionName expoBeaconPackage.version
    minSdkVersion 23
  }
  lint {
    abortOnError false
  }
}

dependencies {
  implementation 'org.altbeacon:android-beacon-library:2.21.2'
}
